services:
  jupyterbundle.widgets.JupyterWidgets:
    tags:
      - "widgets.factory"

  jupyterbundle.notebook.DataFrameDisplay:
    tags:
      - {name: 'pysparkbundle.dataframe.show_method', alias: jupyter_display}
